### ISSUE TITLE
Inefficient processing of cones

### ISSUE THREAD

**Issue by aszekMosek** [cvxgrp/CVXR#137]
**Issue**

It seems CVXR has some inherent inefficiency in processing cones, especially visible when the number of cones increases.

Consider a simple conic problem requiring ``N`` quadratic cones of dimension 3: minimize sum(t_i^2) subject to t==const.

```
library("CVXR")

N <- 10000;
V = 1.33;
solver <- "MOSEK"; # Or "ECOS", same issue

z = Variable(N);
t = Variable(N);

prob <- Problem(
	Minimize( sum(z) ),
	constraints = list( t==V, z>=t^2 )
	);

sol <- solve(prob, solver = solver, verbose = TRUE, ignore_dcp = FALSE)

print(abs(sol$value - N*V^2))
```

(This is a toy model from a more realistic example. )

The code above either gets the R session killed due to lack of memory or takes forever to complete. It seems to me that somewhere internally CVXR converts some sparse matrix to dense, which kills the performance. In particular I get warnings such as:

```
Warning messages:
1: In .M2v(x) : sparse->dense coercion: allocating vector of size 1.1 GiB
2: In .M2v(x) : sparse->dense coercion: allocating vector of size 1.7 GiB
```

but I am not able to debug it much further.

**Versions**

I used R 4.4, latest CVXR and MOSEK or ECOS, but the problem appears across various versions and solvers.

**Expected behavior**

Adding 10000 3-dim quadratic cones to the model should take no time at all. This has practical applications.

**Comment by bnaras** [comment]
@aszekMosek Thank you for the report.  Indeed, we have seen some issues like this and Anqi and I are working on a new release. But I will investigate this further as soon as I can.

**Comment by bnaras** [comment]
@aszekMosek I've made some progress. Of course, I need to exhaustively check my patches carefully and roll up a release, but I attach the results here, just FYI.  (BTW, `CVXR` hasn't caught up to the newer `CVXPY` releases, but that is in progress...) This also fixes all the warnings about inefficient matrix coercions...

Some timing result comparisons below: old, followed by new.
```
   user  system elapsed 
 35.150   7.613  42.793 
```

```
  user  system elapsed 
  0.873   0.062   0.990 
```
but now it 

[cvxr_issue137.txt](https://github.com/cvxgrp/CVXR/files/15425822/cvxr_issue137.txt)

**Comment by florianpeters** [comment]
@bnaras that sounds great!

Would you be willing to post/share your current patch? Or is the next release coming so soon that it's worth waiting?

I have been experiencing similar performance issues with CVXR. I'd prefer to work with CVXR. But I'd switch to CVXPY if the fix to CVXR needs some time (say weeks rather than days).

**Comment by bnaras** [comment]
@florianpeters I've merged the changes into the master branch (version 1.0-13 of `CVXR`). CRAN upload is in process.

**Comment by bnaras** [comment]
Version 1.1-13 is now on CRAN and the builds for platforms will soon appear.

**Comment by florianpeters** [comment]
@bnaras fantastic! The new release works amazingly well on @aszekMosek's example and significantly improves performance on more complex optimization problems as well. Thanks for rolling out the new release so quickly!

**Comment by bnaras** [comment]
Great, thank you both.  I will close this ticket.
