### ISSUE TITLE
Feature request: consistent iteration max arguments across solvers

### ISSUE THREAD

**Issue by karldw** [cvxgrp/CVXR#42]
Thanks for the really useful package! I've run across a couple of small small issues when trying to adjust the number of iterations.

1. The names of the arguments to control the number of iterations is different for SCS and ECOS (and presumably the other solvers)
    - `max_iters` for SCS and `MAXIT` for ECOS
    - There's no warning if you set the wrong argument name – it just silently uses the default. Would it be possible to check that the provided `...` arguments are control arguments the solver uses?
2. Reaching a user-set maximum iteration count leads to a solver failure in ECOS, but `solved_inaccurate` in SCS. (In contrast, hitting the _default_ ECOS iteration count gives `solved_inaccurate`)

**Comment by bnaras** [comment]
I'm going to close this issue because it is addressed now. See https://cvxr.rbind.io/cvxr_examples/cvxr_solver-parameters/
