### ISSUE TITLE
View all results from CVXR

### ISSUE THREAD

**Issue by kevinegan31** [cvxgrp/CVXR#58]
I am currently using CVXR to develop Lasso results. I am using the “SCS” solver and see that it goes through 5000 iterations. Is it possible to see the results of each of these iterations? I am hoping to develop a plot from the results.

Thanks

**Comment by bnaras** [comment]
You mean something more detailed than what the `verbose = TRUE` param to `solve()` provides? 
I would think that depends on what the specific solver wants to expose. A crude approach would be set the number of iterations from 1 to 5000 and get the results.
