### ISSUE TITLE
unable to install on ubuntu bionic 18.04

### ISSUE THREAD

**Issue by dev-spk** [cvxgrp/CVXR#74]
**Describe the bug** 
I am unable to install on Ubuntu. Package compiled successfully. Something went wrong afterwards.
The last few lines of error are shown below.

**Output**
installing to /home/s/R/x86_64-pc-linux-gnu-library/3.4/CVXR/libs
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
Creating a generic function for ‘is.element’ from package ‘base’ in package ‘CVXR’
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘CVXR’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘CVXR’
Error in attr(prototype, slotName) <- attr(pri, slotName) : 
  invalid first argument
Error : unable to load R code in package ‘CVXR’
ERROR: lazy loading failed for package ‘CVXR’
* removing ‘/home/s/R/x86_64-pc-linux-gnu-library/3.4/CVXR’
Warning in install.packages :
  installation of package ‘CVXR’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpIe6y6V/downloaded_packages’
> library(CVXR)
Error in library(CVXR) : there is no package called ‘CVXR’

**Version**
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4  tools_3.4.4     grid_3.4.4      lattice_0.20-35

**Comment by bnaras** [comment]
I note several things.
- You seem to be a somewhat ancient version of R (3.4.x released 2017ish?). 
- This error message is not from `CVXR`. 
- The error is most likely something to do with your R installation.
Upgrading your R to something recent will fix your problems.

**Comment by dev-spk** [comment]
Thank you. Installed smoothly on R4.01.
Didn't support for R3.4, 3.5 or 3.6.
