### ISSUE TITLE
mul_elemwise() deprecated?

### ISSUE THREAD

**Issue by robohyun66** [cvxgrp/CVXR#75]
A quick question: I'm getting the error
`'mul_elemwise' is not an exported object from 'namespace:CVXR'`

I can see that `multiply()` seems to do the same thing. `mul_elemwise()` only exists in documentation but not in the package anymore, from a cursory search. Is it deprecated?

**Comment by anqif** [comment]
Yes, mul_elemwise has been renamed to multiply. We will update the documentation shortly.
