### ISSUE TITLE
Problem does not follow DCP rules

### ISSUE THREAD

**Issue by flodel** [cvxgrp/CVXR#78]
**Describe the bug** 
Solver claims that my problem does not follow DCP rules. The small reproducible example provided below should be equivalent to an unconstrained `Minimize(sum_entries(pos(errors_values)))` where `errors_values` is a 3-by-3 matrix of randomly generated values. Which is obviously linear/convex.

**To Reproduce**
```
library(CVXR)
errors_values <- matrix(rnorm(3*3), 3, 3)
errors <- Variable(3, 3)
costs <- Variable(3, 3)
total_cost <- Variable(1)
objective <- Minimize(total_cost)
constraints <- list(
  errors == errors_values,
  costs == pos(errors),
  total_cost == sum_entries(costs)
)
problem <- Problem(objective = objective, constraints = constraints)
result <- solve(problem)
```

**Expected behavior**
For the solver to run and return with an optimal status and objective value equal to `sum(pmax(errors_values, 0))`.

**Output**
`Error in construct_intermediate_chain(object, candidate_solvers, gp = gp) : 
  Problem does not follow DCP rules. However, the problem does follow DGP rules. Consider calling this function with gp = TRUE`

**Version**
```> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] CVXR_1.0-1

loaded via a namespace (and not attached):
 [1] bit_4.0.4       compiler_3.6.3  R6_2.4.1        Matrix_1.2-18  
 [5] tools_3.6.3     gmp_0.6-0       Rcpp_1.0.4      bit64_4.0.2    
 [9] grid_3.6.3      Rmpfr_0.8-1     lattice_0.20-38
```

**Additional context**
Running the solver with `gp = TRUE` as suggested by the error message above returns an opposite error, claiming the problem now does follow DCP rules, which I believe is true.

I also tested adding `nonneg = TRUE` to the `Variable()` definition of `costs` and `total_costs`. It does not help.

This small reproducible example was inspired from a much more complex production process, which was running fine in a previous version of R and CVXR.

Thanks if you can have a look and provide feedback soon.

**Comment by koenvandenberge** [comment]
I'm running into a similar issue.
