### ISSUE TITLE
mac mini m1 silicon --- try the catenary example

### ISSUE THREAD

**Issue by horowo** [cvxgrp/CVXR#93]
**Describe the bug** 

**To Reproduce** 
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior. We show a marked preference for a [reprex](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) with session information included (see below); it will significantly improve the probability/time of a reply from the developers.

**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
If you use [reprex](https://reprex.tidyverse.org), include the session info via `reprex(..., session_info = TRUE)`. Otherwise, paste the output of `sessionInfo()` in your R session in a verbatim section. 

**Additional context**

**Lastly**

Don't forget to preview your report using the `Preview` tab. Unless we can see things clearly marked up, your report will most likely percolate down to the bottom of the pile.

**Comment by bnaras** [comment]
Closing this issue because no reprex provided. Besides the example all works.
